version: '3.4'

services:
  valuationarybackend:
    image: valuationarybackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4100:4100
